# Copyright (c) 2026 Salvo Giangreco
# SPDX-License-Identifier: GPL-3.0-or-later

# Platform configuration file for Qualcomm Snapdragon 888 devices (sm8350)
TARGET_BOARD_API_LEVEL=30
TARGET_PRODUCT_SHIPPING_API_LEVEL=30

# Partitions
TARGET_BOOT_PARTITION_SIZE=100663296
TARGET_DTBO_PARTITION_SIZE=25165824
TARGET_VENDOR_BOOT_PARTITION_SIZE=100663296
TARGET_CACHE_PARTITION_SIZE=629145600

# Dynamic partitions
TARGET_USE_DYNAMIC_PARTITIONS=true
TARGET_SUPER_GROUP_NAME="qti_dynamic_partitions"

# OS
TARGET_OS_SINGLE_SYSTEM_IMAGE="qssi"
TARGET_OS_BUILD_SYSTEM_EXT_PARTITION=false

# SEC Product Feature
TARGET_BLUETOOTH_SUPPORT_A2DPSINK_PROFILE=true
TARGET_BLUETOOTH_SUPPORT_A2DP_SBM=false
TARGET_BLUETOOTH_SUPPORT_HEAD_SAR_BACKOFF=false
# [
# The S21 FE 5G has no XLNA control, so this should be false. It is kept
# true to match the qssi source: with source and target equal, the
# bluetooth patch skips the "Disable SUPPORT_XLNA_CONTROL" smali patch,
# which no longer applies to the Bluetooth.apk shipped in the current
# source firmware (missing ScanManager$ScanNative.smali, changed
# AdapterService.smali context) and aborts the build.
# The variable only selects that patch; it writes no floating feature.
# Set back to false once unica/patches/bluetooth/xlna is regenerated.
TARGET_BLUETOOTH_SUPPORT_XLNA_CONTROL=true
# ]
TARGET_WLAN_CONFIG_CONNECTION_PERSONALIZATION="0"
TARGET_WLAN_CONFIG_CPU_CSTATE_DISABLE_THRESHOLD="100"
TARGET_WLAN_CONFIG_DATA_ACTIVITY_AFFINITY_BOOSTER_THRESHOLD="0"
TARGET_WLAN_CONFIG_DYNAMIC_SWITCH="0"
TARGET_WLAN_CONFIG_L1SS_DISABLE_THRESHOLD="0"
TARGET_WLAN_SUPPORT_80211AX=true
TARGET_WLAN_SUPPORT_80211AX_6GHZ=false
TARGET_WLAN_SUPPORT_APE_SERVICE=false
TARGET_WLAN_SUPPORT_LOWLATENCY=true
TARGET_WLAN_SUPPORT_MBO=true
TARGET_WLAN_SUPPORT_MIMO=true
TARGET_WLAN_SUPPORT_MOBILEAP_5G_BASEDON_COUNTRY=false
TARGET_WLAN_SUPPORT_MOBILEAP_6G=false
TARGET_WLAN_SUPPORT_MOBILEAP_DUALAP=false
TARGET_WLAN_SUPPORT_MOBILEAP_OWE=false
TARGET_WLAN_SUPPORT_MOBILEAP_POWER_SAVEMODE=true
TARGET_WLAN_SUPPORT_MOBILEAP_PRIORITIZE_TRAFFIC=true
TARGET_WLAN_SUPPORT_MOBILEAP_WIFI_CONCURRENCY=true
TARGET_WLAN_SUPPORT_MOBILEAP_WIFISHARING_LITE=true
TARGET_WLAN_SUPPORT_SWITCH_FOR_INDIVIDUAL_APPS=true
TARGET_WLAN_SUPPORT_TWT_CONTROL=false
TARGET_WLAN_SUPPORT_WIFI_TO_CELLULAR=true
